### ISSUE TITLE
License is not specified

### ISSUE THREAD

**Issue by KOLANICH** [dalemyers/CSV-to-LaTeX-Table#6]
Is it a proprietary piece of software? If it isn't, please specify a license. I personally recommend Unlicense.

**Comment by dalemyers** [comment]
Just added the MIT license.

**Comment by KOLANICH** [comment]
Thank you. Expect some PRs in future.

**Comment by dalemyers** [comment]
Go for it. I've not touched this in 4 years. I created it as a quick and dirty hack when working on my masters dissertation and haven't used since. I've considered coming back and beefing it up a little (and fixing all the awful code in it), but it's never been a priority.
